### ISSUE TITLE
Another UI bug: Proposal slider bugged out / out of proportion?

### ISSUE THREAD

**Issue by anthonyoliai** [1Hive/honey-pot#100]
I'm not sure if this has been discussed before, but on the proposal page of 1hive, I noticed that the slider seems to not function. If I have time later this week I'll look into it. 

![10e94badc8e99b5ce8aa7ddda68ff144](https://user-images.githubusercontent.com/61785803/95243390-e20e0280-0810-11eb-8cf2-1aa74070909f.png)

EDIT: After further examination I've figured out why this happens. The reason why this is happening is because of the very small amount of HNY entered in the prompt asking how much HNY you want to support. Entering a small amount such as 0.0001 makes the slider crash.

**Comment by onbjerg** [comment]
Can be replicated if you support a proposal for the first time and you enter a very small number (e.g. 0.000001)

**Comment by onbjerg** [comment]
This seems to have been solved in v2, can you confirm?

**Comment by anthonyoliai** [comment]
Can confirm that this has been fixed in v2.
