### ISSUE TITLE
Remove Portis as a suggested wallet

### ISSUE THREAD

**Issue by onbjerg** [1Hive/honey-pot#154]
![image](https://user-images.githubusercontent.com/8862627/96819394-c2d3bf80-1423-11eb-9a4c-2c6a868139cf.png)

**Comment by famole** [comment]
I'm taking this one

**Comment by famole** [comment]
I'm leaving the PR here https://github.com/1Hive/honey-pot/pull/156
Not sure why it wasn't added to the original issue.

@rperez89 @fabriziovigevani

**Comment by felixbbertrand** [comment]
Maybe close this issue guys, since its fix. @onbjerg

**Comment by fabriziovigevani** [comment]
Closed by #156
