### ISSUE TITLE
Make the search bar case-insensitive

### ISSUE THREAD

**Issue by felixbbertrand** [1Hive/honey-pot#198]
atm : 
![image](https://user-images.githubusercontent.com/40891827/104982622-0dd88100-59d9-11eb-8e7a-3f6a58aca55e.png)
![image](https://user-images.githubusercontent.com/40891827/104982637-1630bc00-59d9-11eb-94e0-a31205a29e11.png)

Both should display the same search.

**Comment by felixbbertrand** [comment]
@thr3m

**Comment by 0xGabi** [comment]
duplicated of #150
