### ISSUE TITLE
Raise Dispute Modal

### ISSUE THREAD

**Issue by rperez89** [1Hive/honey-pot#210]
https://www.figma.com/file/Kz35QDzg8uUCHDK7jjipRx/AN-Dashboard-(Phase-3)?node-id=1708%3A1

**Comment by fioreb** [comment]
This figma file have the idea for the modal when the user needs to upload a file or use rich text
https://www.figma.com/file/P06HTzSyb9hExJVpwaUPmA/Honey-Pot-2.0?node-id=2134%3A468
