### ISSUE TITLE
Allow Lock Manger - Toggle Issue - Under Stake Management

### ISSUE THREAD

**Issue by projectuwb** [1Hive/honey-pot#253]
Sequence of events that lead to the issue
1. Clicked on "Allow lock manager" under Stake Management
2. Approved tx on metamask 
3. Tx mined and got confirmation 
4. The "Allow lock manager" toggle switch is not functional 
5. Tried to reload and click the toggle which did not respond. 
6. Disconnected the wallet and re-connected 
7. Issue seem to self rectify after step 6.

**Comment by fabriziovigevani** [comment]
What's your Ethereum address? 

Could you provide a screenshot of the the Staking Managment view?

**Comment by projectuwb** [comment]
Info supplied on Discord DM

**Comment by fabriziovigevani** [comment]
@rperez89 we may need to do a polling of the allowed info?

**Comment by 0xGabi** [comment]
This issue didn't occur anymore. If it's detected again re-open the issue.
