### ISSUE TITLE
BUG: Support Proposal Failed

### ISSUE THREAD

**Issue by divine-comedian** [1Hive/honey-pot#256]
I'm attempting to  support a proposal and the transaction fails, I have tried several times with varying gas amounts. Brave Browser on Metamask. 

![image](https://user-images.githubusercontent.com/67759413/110127942-38697800-7d94-11eb-984f-5248214f8ec4.png)

What I could see from the contract errors on etherscan:
![image](https://user-images.githubusercontent.com/67759413/110127907-2c7db600-7d94-11eb-8ea5-4530c5fc747f.png)

**Comment by rperez89** [comment]
Just tried and also had the issue then i set a higher gas amount and worked, going to check the gas that we are using as default 
<img width="963" alt="Screen Shot 2021-03-05 at 12 48 20 PM" src="https://user-images.githubusercontent.com/11763623/110138936-45e12b00-7db1-11eb-9ad6-0cec70bc7373.png">

https://rinkeby.etherscan.io/tx/0xb3176ec4c70fb38294226e19355986afdf6e4a6702aa95c8a6202d19737f5b10

**Comment by fabriziovigevani** [comment]
closed by #259
