### ISSUE TITLE
Suggestion: Add Timestamp to detailed proposal view

### ISSUE THREAD

**Issue by divine-comedian** [1Hive/honey-pot#257]
When you're scrolling the list of proposals/actions there is a timestamp of when it was created. It would be nice to have that same timestamp when you're looking at the detailed proposal view

![image](https://user-images.githubusercontent.com/67759413/110129598-1ffa5d00-7d96-11eb-8794-c15a7f9e0ba9.png)

**Comment by willjgriff** [comment]
@fioreb Where would be good to put the timestamp in the detail view above?

**Comment by fioreb** [comment]
> @fioreb Where would be good to put the timestamp in the detail view above?

I think we can place it here to keep consistency with the feed but not below so we don't add unnecessary height to the box

<img width="325" alt="Screen Shot 2021-03-12 at 12 03 05" src="https://user-images.githubusercontent.com/61423083/110958001-f78cd880-832a-11eb-921c-1698b1047b59.png">

**Comment by fabriziovigevani** [comment]
closed by #356
