### ISSUE TITLE
Status sync between Honeypot and Celeste

### ISSUE THREAD

**Issue by projectuwb** [1Hive/honey-pot#260]
Issue: Status between Honeypot and Celeste seems to not sync automatically and requires 'Disconnect' and then 'Connect' to have it sync.
1. Created proposal #20 on Honeypot https://honey-pot-git-disputable-version-1hive.vercel.app/?#/proposal/20
2. Got challenged and chose to "Raise to Celeste" option
3. Celeste term was not up to date and needed update
4. Processed first tx to update, the term only updated for a few seconds? Unsure why.
5. Did not realise issue above and tried the "Raise to Celeste" option and got error as described here https://discord.com/channels/698287700834517064/762754201364987924/817819883072126977
6. Processed second tx to update term, term updated for 10 m
7. Honeypot has not synced with this info and error in Step 5 persists when tying the "Raise to Celeste" option
8. Disconnect and Connect wallet again
9. Issue seems resolved and allows action.

**Comment by fabriziovigevani** [comment]
closed by #261
