### ISSUE TITLE
Stake management page is confusing... I have to both deposit and allow?!?!? this is unclear...

### ISSUE THREAD

**Issue by GriffGreen** [1Hive/honey-pot#263]
Just tell me to do one or the other. I'm not excited about making this choice...

<img width="1072" alt="Screen Shot 2021-03-07 at 9 51 36 AM" src="https://user-images.githubusercontent.com/14945613/110244011-1707b800-7f5d-11eb-8a8c-cfd3f801df1c.png">

**Comment by rperez89** [comment]
Ah yes you need to deposit and then allow the agreement app to make use of your staked funds, which behaviour would you expect? to stake and also automatically allow ? i think there was some stuffs behind that cc @willjgriff

**Comment by GriffGreen** [comment]
The Switch makes it feel Optional... it would be nice to have a 1, 2, 3, step process... so i know that for it to be done I have to do all 3 steps

**Comment by fabriziovigevani** [comment]
Closing as this was handled in #336
