### ISSUE TITLE
.1 Hny is a fine action deposit now... but what happens when HNY is worth 500k? We have to have Governance? I would like the action amount to be relative to a stable token rather than a volatile token...

### ISSUE THREAD

**Issue by GriffGreen** [1Hive/honey-pot#265]
Can we use the same magic for the action amount that is used for stable proposal requests?

So that the action amount is set to 50 xDai worth of HNY or something like that

<img width="398" alt="Screen Shot 2021-03-07 at 9 43 48 AM" src="https://user-images.githubusercontent.com/14945613/110243947-dc058480-7f5c-11eb-9016-7a02cbe1282c.png">

<img width="618" alt="Screen Shot 2021-03-07 at 10 11 58 AM" src="https://user-images.githubusercontent.com/14945613/110244623-deb5a900-7f5f-11eb-9fad-dd9e8acc3ed1.png">

**Comment by kaselol** [comment]
Is this celeste testnet?

**Comment by rperez89** [comment]
This one makes sense to me!

**Comment by willjgriff** [comment]
Yeah we've considered this, we have automatic adjustment of Celeste fees, we'll look into doing the same to the action and challenge fees.

**Comment by GriffGreen** [comment]
Ok @willjgriff so this is out of scope for MVP launch :-D?

**Comment by fabriziovigevani** [comment]
Closing as this was handled in https://github.com/1Hive/agreement/pull/4
