### ISSUE TITLE
Made a funding proposal but then I don't see an option to vote on it

### ISSUE THREAD

**Issue by GriffGreen** [1Hive/honey-pot#266]
Sem is a sweet heart proposal didn't pop up... not sure why

<img width="978" alt="Screen Shot 2021-03-07 at 10 19 02 AM" src="https://user-images.githubusercontent.com/14945613/110244858-02c5ba00-7f61-11eb-9528-faecfbc4deec.png">

**Comment by GriffGreen** [comment]
Tried 4 times and the 4th time worked

Here is what i was putting in: 

<img width="649" alt="Screen Shot 2021-03-07 at 10 22 23 AM" src="https://user-images.githubusercontent.com/14945613/110245033-e8401080-7f61-11eb-81ac-3b4532172462.png">

**Comment by rperez89** [comment]
hmm you mean that you created the proposal and you couldn't find it on the proposal list?

**Comment by GriffGreen** [comment]
it seems like the proposal page was just refreshing when i clicked the button and never actually submitted it

**Comment by fabriziovigevani** [comment]
closed by #479
