### ISSUE TITLE
The red thumbs down, at first glanse, makes me think i voted no... but really i voted yes!

### ISSUE THREAD

**Issue by GriffGreen** [1Hive/honey-pot#267]
I know that this is an action option... and that it says "Supported" but at first glance, i see the pictures and it makes me think i voted no!

Maybe make the actions words (Support & Remove Support) and make the picture depict the current vote?

<img width="389" alt="Screen Shot 2021-03-07 at 10 36 27 AM" src="https://user-images.githubusercontent.com/14945613/110245479-95ffef00-7f63-11eb-9fb8-2d2976773327.png">

**Comment by fabriziovigevani** [comment]
closed by #478
