### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by willjgriff** [1Hive/honey-pot#290]
On the staking screen when depositing collateral, the warning should read: "You will be able to withdraw your collateral balance at any time, except for any that is locked on a scheduled proposal."
<img width="682" alt="Screenshot 2021-03-12 at 15 11 56" src="https://user-images.githubusercontent.com/9317743/110959122-4a738980-8345-11eb-98fb-c8f981bc38ab.png">

This proposal is cancelled yet I can still stake on it. #17 for reference. If I try to stake it fails. Presumably we don't need to let the user explicitly unstake because anything in cancelled proposals should be take into account on the UI? In which case can we remove the support button in this situation?
<img width="931" alt="Screenshot 2021-03-12 at 15 25 44" src="https://user-images.githubusercontent.com/9317743/110961043-47799880-8347-11eb-9c60-a5f162b5eab7.png">

No table entry added to the stake screen for the previously cancelled proposal. The available Honey has updated but there's no indication as to why. Turns out I need to refresh and reconnect my wallet before it updates.
<img width="1182" alt="Screenshot 2021-03-12 at 15 35 00" src="https://user-images.githubusercontent.com/9317743/110962129-83f9c400-8348-11eb-9b11-07868c539375.png">

The warning on the right for a suggestion should read: "The suggestion will exist until it is challenged or removed."
<img width="1240" alt="Screenshot 2021-03-12 at 15 50 46" src="https://user-images.githubusercontent.com/9317743/110964096-b99fac80-834a-11eb-9254-28dca0a08f11.png">

Can we remove the ` at the start of the error message at the bottom.
<img width="697" alt="Screenshot 2021-03-11 at 13 53 41" src="https://user-images.githubusercontent.com/9317743/110965091-c96bc080-834b-11eb-9d90-b35a5ffde341.png">

"remaining" should be "remainder".
<img width="884" alt="Screenshot 2021-03-11 at 13 58 31" src="https://user-images.githubusercontent.com/9317743/110965226-e607f880-834b-11eb-8533-171c02bd8b18.png">

When challenging an action this needs to be laid out better. 
The action collateral message should remove the "Your wallet balance is 18 HNY."
The dispute fees message should remove the "This balance will be returned to your account if the submitter accepts your settlement offer or if you win the dispute raised to Celeste."
The dispute fees warning should say "lock" instead of "pay".
There should be an info box at the bottom saying "The action collateral and dispute fees will be returned to your account if the submitter accepts your settlement offer or if you win the dispute raised to Celeste. Your wallet balance is 18 HNY."
<img width="655" alt="Screenshot 2021-03-12 at 16 10 56" src="https://user-images.githubusercontent.com/9317743/110966767-8a3e6f00-834d-11eb-9b09-cc88365c312e.png">

Should read "This proposal has been challenged but you can continue to support it to increase conviction. When the challenge is resolved, if allowed, the proposal will be resumed otherwise this proposal will be cancelled."
<img width="859" alt="Screenshot 2021-03-12 at 16 27 15" src="https://user-images.githubusercontent.com/9317743/110968789-d8ed0880-834f-11eb-8ea3-0e60dedd9423.png">

This should read "If you specify the proposal amount in DAI it will be converted to HNY at the time of execution."
<img width="608" alt="Screenshot 2021-03-12 at 16 41 37" src="https://user-images.githubusercontent.com/9317743/110970611-d1c6fa00-8351-11eb-8d03-66073d30db9a.png">

The links to the proposal from the staking manager don't work for me. They just go to home.

The modals disappear regularly. I've noticed if I click in the modal and remove the click after dragging the mouse outside of it, it will disappear. Can this be prevented? Of course clicking outside should still close it.

Also the modals don't disappear after a transaction has been processed, you have to click them away. I think they should close automatically.

The links to celeste are broken because it uses "questions" in the URL instead of "disputes".

I've noticed when depositing in the staking manager my transaction sometimes fails because the gas limit is set too low. Can it default to a higher value? Tx: https://rinkeby.etherscan.io/tx/0xf94d4f4b10e38eb5d42a9e18cd9a9688072e7a6f9f8b91c1855f6e321686d881

**Comment by fabriziovigevani** [comment]
Closed by #305
