### ISSUE TITLE
Add a Create Proposal button to Sign Covenant view

### ISSUE THREAD

**Issue by sachayves** [1Hive/honey-pot#297]
![](https://i.imgur.com/65rq2k9.png)

**Problem**
Once the transaction has been mined, it's not clear what one should do next. A user is in all probably here because they are trying to create a proposal.

**Suggestion**
Add a ~~`Continue creating proposal`~~ `Create proposal` button to this view: should appear once the `Sign Covenant` transaction has been mined; takes you directly to the `Submit action requirements` view.

**Comment by lkngtn** [comment]
I think this makes sense, Its possible for someone to just want to sign the covenant and not create a proposal, but it wouldn't really cause any trouble if that's the case, and would certainly make it a bit more straightforward if they were prompted to sign because they were trying to create a proposal.

**Comment by sachayves** [comment]
Right. In that case, we could rename to `Create Proposal` to minimise room for confusion.

**Comment by willjgriff** [comment]
This modal should close as soon as the transaction is finalised. I don't think we need to add these buttons for now tbh. We should revisit the whole flow in the future though, ideally we should know if someone has come from the create proposal screen and return them to it automatically once the transaction is finalised.

**Comment by sachayves** [comment]
>  ideally we should know if someone has come from the create proposal screen and return them to it automatically once the transaction is finalised.

Agree this is the desired flow.

In the meantime, perhaps we could offer some sort of confirmation that the covenant was signed successfully, and then redirect to home?

**Comment by rperez89** [comment]
> This modal should close as soon as the transaction is finalised. I don't think we need to add these buttons for now tbh. We should revisit the whole flow in the future though, ideally we should know if someone has come from the create proposal screen and return them to it automatically once the transaction is finalised.

I don't think we should close the modals automatically , the modals has some animations and info to read like the trx it will be a bit agressive to close it once ready

**Comment by sachayves** [comment]
> I don't think we should close the modals automatically , the modals has some animations and info to read like the trx it will be a bit agressive to close it once ready

I'm mixed on this too. There is certainly an advantage to not closing the modals: you give the reader more options: they can double check the transaction, and you can suggest to them next steps.

**Comment by sachayves** [comment]
Having said that, if you have a way of redirecting them to where they came from / anticipate where they are trying to go, then you don't really need to provide them with suggestions of possible next steps.

**Comment by sachayves** [comment]
Either way, we do need a success confirmation that's more informative than just `transaction mined`.

**Comment by rperez89** [comment]
> Having said that, if you have a way of redirecting them to where they came from / anticipate where they are trying to go, then you don't really need to provide them with suggestions of possible next steps.

I think that adds a really weird behaviour, you really don't know if the user once finish creating the proposal wants to check his own proposal, wants to go and check how looks others proposals, wants to check the feed with the top proposals, the newest proposals , etc

**Comment by sachayves** [comment]
>  you really don't know if the user once finish creating the proposal wants to check his own proposal, wants to go and check how looks others proposals, wants to check the feed with the top proposals, the newest proposals , etc

If you're talking about what the expected behaviour is after creating a proposal, I'm pretty sure the first reaction will almost always be to double check that the proposal has indeed been successfully created.

As it stands, the current UI just leaves us hanging...

**Comment by sachayves** [comment]
So the most important thing here are suitable confirmation messages, and not disrupting user flow.

**Comment by rperez89** [comment]
> Either way, I think we do need a success confirmation that's more informative than just `transaction mined`.

we are showing the trx hash, what other relevant info about the trx would you show more than the trx state and the hash? 
<img width="643" alt="Screen Shot 2021-03-16 at 8 29 29 AM" src="https://user-images.githubusercontent.com/11763623/111302557-522b7a80-8632-11eb-8a80-c99ddcba2e9d.png">

**Comment by sachayves** [comment]
@rperez89 Yes, it's really not clear what one should do next at this stage. Ok, transaction has been mined, that's great. But what I really care about is **whether the Covenant has been signed.** It's a subtle but important difference.

The second thing is, if the user was redirected here because she was trying to create a proposal, it should be dead easy for her to carry on from where she left off (she should not be made to think).

Honestly, my first instinct was just to wait and see if there was a next step suggested to me (so that I could carry on with creating the proposal). But nothing came up, so my only choice was to click `X`. Then I had to think about what to do next to try and achieve my original goal (go back to Home, and the click on Create Proposal again) -- making the user think like this when you should be able to anticipate her next action, is terrible UX.

**Comment by fioreb** [comment]
All you have fair points on this.

I think closing the modals automatically maybe is not the best way to go, because the user maybe will feel that he/she lost some information, which can be frustrating. 

I think it is important to take into account the behavior in other sites because the user is already used to it, but I also think that what we need to take into account is as Sasha said, anticipate what the user is going to need to do, that is why I think it's a good idea to add the Create proposal button, we can add it disabled and when the transaction ended successfully abled it so the flow can continue.

**Comment by fabriziovigevani** [comment]
Initially i was in favor of what @willjgriff suggested to automatically close the modal when the last tx is mined, but reading from this convo y think is going to be better UX to direct the user to Create a proposal or direct them to the home page.
Besides i would say that 90% of users signing the covenant for example are going to come from the create proposal modal flow.

> Create proposal button, we can add it disabled and when the transaction ended successfully abled it so the flow can continue.

Maybe we could just not show it instead of having it disabled?

**Comment by fioreb** [comment]
> Initially i was in favor of what @willjgriff suggested to automatically close the modal when the last tx is mined, but reading from this convo y think is going to be better UX to direct the user to Create a proposal or direct them to the home page.
> Besides i would say that 90% of users signing the covenant for example are going to come from the create proposal modal flow.
> 
> > Create proposal button, we can add it disabled and when the transaction ended successfully abled it so the flow can continue.
> 
> Maybe we could just not show it instead of having it disabled?

I thought about that at first but then the idea of a button appearing stop me, but yes we can do that!

**Comment by rperez89** [comment]
addressed on #336
