### ISSUE TITLE
Clarify the link between Deposit and Stake

### ISSUE THREAD

**Issue by sachayves** [1Hive/honey-pot#298]
![](https://storage.googleapis.com/ethereum-hackmd/upload_4b7c4c930d32a5e0ae07f66d8de28df0.png)

**Problem:**
Prior to this view, we've only referred to the need to *stake* HNY. The word *deposit* hasn't been mentioned. This view introduces the term deposit, without linking it to the term stake.

**Suggestion:**
Make it clear that the two terms are linked. Rename `Deposit` to `Deposit (stake)`.

**Comment by willjgriff** [comment]
@rperez89 I think these buttons should be the other way round and we should rename stake manager to deposit manager (see Discord for discussion).

**Comment by willjgriff** [comment]
We've renamed so no longer using the term stake. Hopefully this is clearer.
