### ISSUE TITLE
Add a Create Proposal button to Deposit HNY view (and combine with lock manager step if possible)

### ISSUE THREAD

**Issue by sachayves** [1Hive/honey-pot#299]
![](https://storage.googleapis.com/ethereum-hackmd/upload_57ce6b42a09891639141a58a5805f238.png)

**Problem:**
Transactions mined! Great. But again, not clear what one should do next.

**Suggestion:**
Add a `Create proposal` button: appears once the Stake HNY transaction has been mined and takes you directly to the `Submit action requirements` view.

*Even better* if we could integrate `Allow lock manager` as the third step here.

**Comment by willjgriff** [comment]
Again this modal will disappear once the transactions are finalised and the general flow should be thought about more to fix the above UX issue.

**Comment by sachayves** [comment]
Got it. So, I think just giving permissions to the lock manager as part of this step would be a huge win.

So:
1. Approve HNY
2. Stake HNY
3. Allow lock manager

Then redirect back to the `Submit action requirements` view?

**Comment by willjgriff** [comment]
> Got it. So, I think just giving permissions to the lock manager as part of this step would be a huge win.

Yeah I agree with this, in the case the lock/collateral manager isn't currently allowed.

**Comment by rperez89** [comment]
addressed on #336
