### ISSUE TITLE
Add a View Proposal button to the Create Transaction view

### ISSUE THREAD

**Issue by sachayves** [1Hive/honey-pot#302]
![](https://storage.googleapis.com/ethereum-hackmd/upload_e096fa2d63c6402de0ca8d1e1dea15f2.png)

![](https://storage.googleapis.com/ethereum-hackmd/upload_b188f7c4145f720330a98a598f12378f.png)

**Problem**
It's not clear what the one should do next (after the transaction has been mined). If the user exits the `Create transaction` view (the only thing she can do) she is re-directed to the Home view. But the Proposal List in the Home view defaults to  the `TOP` filter, so she  won't immediately see her proposal.

![](https://storage.googleapis.com/ethereum-hackmd/upload_f60bf21138b9d4cfeee1251a97096ac3.png)

She is left wondering whether her proposal went through correctly.

**Suggestion**
Add a `View proposal` button to the `Create transaction` view (assuming this view is only used to submit an action): it should appear once the transaction has been mined and take the user directly to the proposal.

**Comment by willjgriff** [comment]
@rperez89 Can we open to the new proposals screen once the transaction is finalised? Since we will be closing these modals after the transactions have been finalised.

**Comment by rperez89** [comment]
Sacha and fiore decided to do this bulk of issues #336 , so closing this one
