### ISSUE TITLE
Deposit HNY as collateral: text clarifications

### ISSUE THREAD

**Issue by sachayves** [1Hive/honey-pot#303]
![](https://storage.googleapis.com/ethereum-hackmd/upload_c2b38e227fe8bae32e8b3f90e4ed6823.png)

**Currently reads:** This amount will be placed in the staking pool and will be used to pay for actions collateral and submission fees, when proposing actions bound by this organization’s Covenant.

**Suggestion:** This HNY will be placed in the staking pool to be used as collateral for any proposals you choose to submit.

----------------------------------

**Currently reads:** You will be able to withdraw your collateral balance any time, except when proposing actions bound by this organisation’s covenant.

**Suggestion:** When you create a proposal, you’ll need to put some collateral at stake (0.1 HNY). You’ll get this back when your proposal is either executed or cancelled. However, if it is successfully challenged in Celeste, this collateral will be awarded to the challenger.

**Comment by sachayves** [comment]
P.S. it's not clear to me what exactly the purpose of the staking pool is, and what the submission fees are used for.

**Comment by willjgriff** [comment]
@rperez89 The message at the top should read: 

"This HNY will be locked in the staking pool and will be used as collateral for proposals you submit. 0.1 HNY is required for each proposal which is returned to you if your proposal is either executed or cancelled. However, if it is successfully challenged, it will be awarded to the challenger."

The message at the bottom I've already suggested changes for so use those, don't use the suggestions from here.

**Comment by sachayves** [comment]
> "This HNY will be locked in the staking pool and will be used as collateral for proposals you submit. 0.1 HNY is required for each proposal which is returned to you if your proposal is either executed or cancelled. However, if it is successfully challenged, the HNY will be awarded to the challenger."

Excellent. Much clearer!

**Comment by rperez89** [comment]
addressed on #336
