### ISSUE TITLE
Disputable Conviction Voting: Proposal creation (stream of consciousness)

### ISSUE THREAD

**Issue by sachayves** [1Hive/honey-pot#304]
I documented my thoughts as I tried to create a proposal.

https://notes.ethereum.org/Y0V1N_WqQFiETRkJKR1ehw?view

Sharing to add context to these suggestions:
https://github.com/1Hive/honey-pot/issues/303, https://github.com/1Hive/honey-pot/issues/302, https://github.com/1Hive/honey-pot/issues/301,
https://github.com/1Hive/honey-pot/issues/300,
https://github.com/1Hive/honey-pot/issues/299,
https://github.com/1Hive/honey-pot/issues/298,
https://github.com/1Hive/honey-pot/issues/297

**Comment by sachayves** [comment]
Update: I've referenced the suggestions inline, to make it clear which pain-point(s) they help solve.

**Comment by rperez89** [comment]
addressed on #336
