### ISSUE TITLE
More suggestions

### ISSUE THREAD

**Issue by willjgriff** [1Hive/honey-pot#307]
Just need to remove the world "permissionlessly" so it should read: "This is the part of your collateral balance that has not been locked in any action yet. You may withdraw it at any time."
<img width="338" alt="Screenshot 2021-03-16 at 11 15 52" src="https://user-images.githubusercontent.com/9317743/111300426-f9b3a780-8648-11eb-9962-3c6794633d11.png">

Should read: "This is the part of your collateral balance that is backing a particular action. This Locked amount will move back to Available after the action is finalised if there are no successful challenges."
<img width="338" alt="Screenshot 2021-03-16 at 11 21 52" src="https://user-images.githubusercontent.com/9317743/111301201-d0dfe200-8649-11eb-8779-2a049baf1c72.png">

Should read: "You cannot disallow the collateral manager from locking your funds at this time because you have some collateral locked in scheduled proposals. Once the proposals are finalised you’ll be able to disallow the collateral manager."
<img width="483" alt="Screenshot 2021-03-16 at 11 23 37" src="https://user-images.githubusercontent.com/9317743/111301412-169caa80-864a-11eb-8e48-9b3159cb890a.png">

Rename to "Allow Collateral Manager".
<img width="362" alt="Screenshot 2021-03-16 at 11 31 23" src="https://user-images.githubusercontent.com/9317743/111302309-2799eb80-864b-11eb-8922-014838b81e29.png">

**Comment by fabriziovigevani** [comment]
Closed by https://github.com/1Hive/honey-pot/pull/309
