### ISSUE TITLE
Update the "Status" filters.

### ISSUE THREAD

**Issue by willjgriff** [1Hive/honey-pot#315]
After discussion at the QA party we should update the status filters to: All, Open, Completed, Removed. Basically just update "Closed" to "Completed". 

Only successfully completed proposals should be in the "Completed" filter. Everything else that isn't open, no matter how it was closed whether by the creator, settled or cancelled by Celeste, should be in the "Removed" filter.

Also @fioreb have you considered the "Type" filter (Suggestion, Proposal, Decision) to be in a drop down box like the others?
<img width="337" alt="Screenshot 2021-03-18 at 10 29 35" src="https://user-images.githubusercontent.com/9317743/111611920-dddd0c80-87d4-11eb-88bf-44de9d73024f.png">

**Comment by fioreb** [comment]
I agree with the changes for the "Status" filter.
Regarding the "Type" filter, the idea to be that way is to differentiate it from the other filters because is more like the essence of the proposal is not something about the state of the proposal itself.
That being said, it wouldn't be wrong if we place it in a dropdown.

**Comment by fioreb** [comment]
It is weird for me that we have at the proposal creation modal:
Signaling proposal
Funding proposal

and then in the filters, we have Suggestion and Oroposal, I think we need to fix that too

**Comment by willjgriff** [comment]
Ah yeah, I think "Signaling proposal" should be updated to "Suggestion" for now in the create proposal modal. I've also updated my comment here for the info box text taking that into account: https://github.com/1Hive/honey-pot/issues/300

**Comment by fioreb** [comment]
Yes, I agree with that!
Thanks for updating the issue 😄

**Comment by willjgriff** [comment]
After discussion in Discord lets also rename "Proposal" to "Funding".

**Comment by fabriziovigevani** [comment]
Closed by #327
