### ISSUE TITLE
Copy changes

### ISSUE THREAD

**Issue by willjgriff** [1Hive/honey-pot#316]
Remove the space.
<img width="860" alt="Screenshot 2021-03-18 at 13 56 54" src="https://user-images.githubusercontent.com/9317743/111637967-cd875a80-87f1-11eb-8ae6-eeb4ce4a0530.png">

"casted" should be "cast".
<img width="348" alt="Screenshot 2021-03-18 at 13 50 08" src="https://user-images.githubusercontent.com/9317743/111636938-db88ab80-87f0-11eb-9d99-b23263de73eb.png">

Update "Stake Management" to "Collateral Manager" and check where stake management/manager is referred to and replace with collateral manager.

**Comment by rperez89** [comment]
Closed by #320
