### ISSUE TITLE
Work out how to use dropdowns in modals.

### ISSUE THREAD

**Issue by willjgriff** [1Hive/honey-pot#319]
I know it's a pain, but this is pretty ugly, it would be great if we could fix this: 

<img width="656" alt="Screenshot 2021-03-18 at 16 57 17" src="https://user-images.githubusercontent.com/9317743/111667637-d46f9680-880c-11eb-8a07-4e0ecd90cd31.png">

**Comment by sachayves** [comment]
Do you mean to replace the radio buttons with a dropdown selection? If so, won't that require more clicks  from the user (2 vs 1)? Or is it a mobile UX thing?

**Comment by fioreb** [comment]
As I mention in the chat, I agree with this! I would prefer to have the dropdown as we were going to have at first time.
There is no way that we can fix the behavior that @rperez89 mention on discord? (about the modal closing when you click an option of the dropdown inside the modal).

Originally we were going to have a third option here, if we will add it at some point, it will get worse 😱

**Comment by sachayves** [comment]
I must admit, I don't see the rationale here. Dropdowns are usually a last resort.

With the current design, not only do you save the user clicks, but you allow them to see the options available to them at a glance -- they don't need to keep anything in their heads (this becomes more, not less, important if a third option is eventually added).

In terms of accessibility, radio buttons are also easier to operate for users who have difficulty making precise mouse movements (see point 8 [here](https://www.nngroup.com/articles/checkboxes-vs-radio-buttons/)

I'm not going to die on this hill, but I am curious as to whether there's any rationale behind the proposed change, apart from it's ugly?

**Comment by fioreb** [comment]
I think you are right Sacha! 
Taking all that into account, it would be a mistake to use a dropdown!

**Comment by rperez89** [comment]
closed by #334
