### ISSUE TITLE
Reloading/blinking conversion in DAI priced proposals. 

### ISSUE THREAD

**Issue by willjgriff** [1Hive/honey-pot#331]
I don't know how often the price is updated in the dai priced proposals but the HNYT conversion amount in the screenshot flashes/loads pretty often. If you keep looking at it long enough it will blink.
<img width="525" alt="Screenshot 2021-03-19 at 11 01 22" src="https://user-images.githubusercontent.com/9317743/111770542-72fa0700-88a2-11eb-8864-a4ea2a0162d0.png">

**Comment by fabriziovigevani** [comment]
Closed by #332
