### ISSUE TITLE
Small issues

### ISSUE THREAD

**Issue by willjgriff** [1Hive/honey-pot#372]
This should read: "This amount will be locked in the collateral manager and will be used as collateral when creating actions bound by this organization's Covenant."
<img width="643" alt="Screenshot 2021-04-08 at 10 36 46" src="https://user-images.githubusercontent.com/9317743/114004273-65f38680-9856-11eb-8bd1-92add4511801.png">

I'm sure I saw this non-wrap around UI issue of the blue bar on the left fixed in Celeste. Can it be fixed here too?
<img width="380" alt="Screenshot 2021-04-08 at 10 35 49" src="https://user-images.githubusercontent.com/9317743/114004510-a18e5080-9856-11eb-82b0-9ffad997d444.png">

Clicking this proposal #0 link should actually take me to vote 0, but it goes to proposal 0 and hangs.
<img width="1277" alt="Screenshot 2021-04-08 at 10 35 16" src="https://user-images.githubusercontent.com/9317743/114004803-e6b28280-9856-11eb-8dcb-01c08d6296b5.png">

Should be: "This amount will be withdrawn from your available balance and directly credited to your enabled account." (lowercase "available" and added full stop)
<img width="631" alt="Screenshot 2021-04-08 at 10 42 33" src="https://user-images.githubusercontent.com/9317743/114005084-224d4c80-9857-11eb-8529-d079559b61fa.png">

Ideally refer to 1hive as 1Hive. I know @lkngtn isn't a fan but it looks like a mistake to me.
<img width="436" alt="Screenshot 2021-04-08 at 10 43 34" src="https://user-images.githubusercontent.com/9317743/114005246-46109280-9857-11eb-9874-57b4726089d0.png">

Lets use caps for the first letter of "Community Covenant".
Also under Action Collateral it should read "You must lock 0.1 HNY as the collateral required to create a proposal. You can manage your balance in the Collateral Manager" (added an r in your and "in the" towards the end).
Also the collateral manager link doesn't work.
<img width="604" alt="Screenshot 2021-04-08 at 11 01 05" src="https://user-images.githubusercontent.com/9317743/114008004-bd472600-9859-11eb-988b-bac338eecede.png">

The funding proposal isn't telling me what threshold I need to pass the vote. Perhaps it's because the vault is empty?
<img width="668" alt="Screenshot 2021-04-08 at 10 55 16" src="https://user-images.githubusercontent.com/9317743/114007075-e915dc00-9858-11eb-98e8-f5c8242472bb.png">

Get this issue when trying to load my profile:
<img width="1093" alt="Screenshot 2021-04-08 at 10 58 08" src="https://user-images.githubusercontent.com/9317743/114007498-4f9afa00-9859-11eb-8bb4-8c0bd772b889.png">

Currency selector drop down seems broken:
<img width="463" alt="Screenshot 2021-04-08 at 10 58 43" src="https://user-images.githubusercontent.com/9317743/114007598-65102400-9859-11eb-908d-ec2bf3bd2b1a.png">

Clicking the thumbs up on the abstain proposal doesn't seem to do anything.
<img width="313" alt="Screenshot 2021-04-08 at 11 03 26" src="https://user-images.githubusercontent.com/9317743/114008333-0dbe8380-985a-11eb-8cca-11f31c5b19fb.png">

**Comment by fabriziovigevani** [comment]
> The funding proposal isn't telling me what threshold I need to pass the vote. Perhaps it's because the vault is empty?

When there isn't a finite threshold number, we show `Proposal might never pass with requested amount` and yeah that's because the vault is empty. 

> Clicking the thumbs up on the abstain proposal doesn't seem to do anything.

@rperez89 Extending on this, might be a more general issue of not being able to interact with the Disputable Conviction Voting app.
![Screen Shot 2021-04-08 at 15 32 52](https://user-images.githubusercontent.com/22663232/114079194-42453600-9880-11eb-9323-b6f0975dd09e.png)

**Comment by rperez89** [comment]
@willjgriff could you try to re publish the manifest, etc for the disputable conviction app?
