### ISSUE TITLE
More issues

### ISSUE THREAD

**Issue by willjgriff** [1Hive/honey-pot#384]
Not finishing submitting evidence when disputing a challenged action:
https://blockscout.com/xdai/mainnet/tx/0x32b3652be6356d14eb5c2eb9f7de6d092789f3aaacc97ff5bbc293160fff2add

There's some confusion over this, lets update it to: "The Settlement Offer is the amount of tokens that you would accept from the proposal submitter in order to cancel the action without raising it to Celeste. This amount, if settled, will be slashed from the proposal submitter's collateral and sent to you so it cannot be greater than the collateral locked for the action but it can be zero."
<img width="468" alt="Screenshot 2021-04-11 at 12 52 46" src="https://user-images.githubusercontent.com/9317743/114303192-d1db2680-9ac4-11eb-8e19-cae1641b5e1e.png">

**Comment by fabriziovigevani** [comment]
> Not finishing submitting evidence when disputing a challenged action:

This was already addressed at https://github.com/1Hive/honey-pot/pull/380
