### ISSUE TITLE
Copy change

### ISSUE THREAD

**Issue by willjgriff** [1Hive/honey-pot#386]
Should be: 
"Celeste has been invoked to settle a dispute with this proposal but you can still support it and increase its conviction. When the dispute is resolved, if allowed, the proposal will continue as normal otherwise it will be cancelled."
<img width="901" alt="Screenshot 2021-04-11 at 22 37 04" src="https://user-images.githubusercontent.com/9317743/114322129-72a60200-9b16-11eb-8f19-b6449851b1db.png">

**Comment by fabriziovigevani** [comment]
I'm not totally convinced by the suggestion. By `processed` someone could mistakenly think that if the dispute is allowed, the proposal would be executed (i recall someone thinking this in Celeste discord chats) and i personally get that as well. Do you think that using the term `resumed` is inaccurate?
