### ISSUE TITLE
Inconsistent Celeste Dispute fee

### ISSUE THREAD

**Issue by willjgriff** [1Hive/honey-pot#394]
When challenging a proposal it says the Celeste dispute fee is 0.04 HNY. This challenged proposal says the fee is 0.08 HNY, can we check which is correct?
<img width="543" alt="Screenshot 2021-04-15 at 09 55 01" src="https://user-images.githubusercontent.com/9317743/114842530-d5c2bd80-9dd0-11eb-8c5e-eadbdd6d517f.png">

**Comment by fabriziovigevani** [comment]
Ah originally this was meant to show both fees paid by the submitter and challenger and i think at some point the label got changed from `fees` to `fee`. Do you think we should display just the fee paid by one party?

**Comment by willjgriff** [comment]
Yeah I think it should show the actual dispute fee. Only 0.04 Honey will ultimately be paid. The other half will be returned to the submitter.

**Comment by fabriziovigevani** [comment]
Yeah that makes sense
