### ISSUE TITLE
Can't support proposal when balance is on abstain.

### ISSUE THREAD

**Issue by willjgriff** [1Hive/honey-pot#395]
I thought if we were staked to abstain we didn't have to withdraw our abstain stake to stake to another proposal. Is that incorrect? 

My Honey is on abstain right now and I can't support another proposal without withdrawing from abstain first.
<img width="724" alt="Screenshot 2021-04-15 at 09 58 47" src="https://user-images.githubusercontent.com/9317743/114843030-4f5aab80-9dd1-11eb-9daf-7711afa6f86c.png">

**Comment by fabriziovigevani** [comment]
As i remember we never had that feature.
The limitation is that the contract only unstakes from the inactive stakes when you are staking on a proposal with a greater amount than you have staked. https://github.com/1Hive/conviction-voting-app/blob/775cf9f7b035fb80b21b0c7d85e9679cbb4c459b/contracts/ConvictionVoting.sol#L453
