### ISSUE TITLE
Thumbs up/down not working.

### ISSUE THREAD

**Issue by willjgriff** [1Hive/honey-pot#404]
Clicking thumbs up/down on proposals does nothing for me. I don't think they're used anyway as they're kind of confusing, can we consider removing them @lkngtn @fioreb? And move the supporters and open status to the row above perhaps?

Current UI for reference:
<img width="532" alt="Screenshot 2021-04-27 at 15 15 01" src="https://user-images.githubusercontent.com/9317743/116256709-57203580-a76b-11eb-860f-1cb32f1b7da3.png">

**Comment by fioreb** [comment]
More users found it confusing? I think we can remove them if that's the case, but I don't have strong feelings about this.
If we remove them, I would prefer to left the supporters and status at the same place because the users are already used to see it there.

**Comment by felixbbertrand** [comment]
+1 on removing the button 
![image](https://user-images.githubusercontent.com/40891827/117379664-ef25c980-aea5-11eb-8c3f-2507faa81d51.png)
My button are green even tho all my HNY is idle

**Comment by fabriziovigevani** [comment]
> My button are green even tho all my HNY is idle

The thumbs up is signaling that you have enough HNY to give some support to the proposal, not that you have supported it (if you had supported it it would show a tag indicator). The purpose of the thumbs up/down is to give a configured % of your HNY balance as support on the proposal. I get that it can be a little bit confusing. Maybe we can remove them for conviction proposals but still have them for Decisions?

I agree with @fioreb on keeping supporter count and status where they are.

**Comment by willjgriff** [comment]
I think this behaviour is pretty confusing and would vote to remove it. Also my thumbs don't do anything when I click them right now. Perhaps they can just be used to signify how you have voted on that proposal?

**Comment by fabriziovigevani** [comment]
Agree that for conviction proposals might be more confusing and we can remove them. I like your suggestion of showing the thumbs up or down signaling your support on Decisions.

**Comment by fabriziovigevani** [comment]
closed by #478
