### ISSUE TITLE
Administrative votes

### ISSUE THREAD

**Issue by rperez89** [1Hive/honey-pot#42]
Once designs are ready we need to create a dandelion voting interface.

Designs Explorations.

https://www.figma.com/file/jBEao1Z0PovUj40tJJG8pY/Honey-Pot-Site?node-id=12%3A9493

**Comment by lkngtn** [comment]
This is related to #45

**Comment by onbjerg** [comment]
Was this fully solved in v2 or is something missing? :blush:

**Comment by rperez89** [comment]
yes we can close this issue
