### ISSUE TITLE
Voting aggregator: Handle aToken balance

### ISSUE THREAD

**Issue by fabriziovigevani** [1Hive/honey-pot#431]
We are cuurrently using `accountBalance` which asumes conviction `stakeToken` is the same as voting `token`, in the case of a garden with Voting Aggregator installed, this is not the case anymore.

**Comment by rperez89** [comment]
this was already fixed right @fabriziovigevani ?

**Comment by rperez89** [comment]
i think. i got a bit confused with this one, we are already taking into account the voting token here <https://github.com/1Hive/honey-pot/blob/8cc835a73c4ae658ea33d33bd175795ed696454f/src/hooks/useExtendedVoteData.js#L17> and not using the stakeToken, or where do you mean that we are doing that?

**Comment by fabriziovigevani** [comment]
Yeah you are right. Thought we were using the `accountBalance` coming from the gardenState instead of fetching it through a contract call. Closing
