### ISSUE TITLE
Back button for gardens list

### ISSUE THREAD

**Issue by fabriziovigevani** [1Hive/honey-pot#443]
Currently there is no back button to go from a garden Home page to the gardens list page.
We could use the usual back button. We should define where's the best place to put it

**Comment by fioreb** [comment]
Can we have like this maybe? https://www.figma.com/file/CCNEARX00L21tCroawNaas/Gardens-MVP1?node-id=380%3A1251
At least for the moment and then when we rethink everything we can come up with a better option

**Comment by fabriziovigevani** [comment]
Sounds good, let's go with this and then see how to improve it

**Comment by fabriziovigevani** [comment]
closed by #485
