### ISSUE TITLE
New Layout (Feed View)

### ISSUE THREAD

**Issue by lkngtn** [1Hive/honey-pot#45]
The new layout will allow us to incorporate dandelion voting proposals along with conviction voting proposals in the same view. It should also help scale for aggregation across gardens in the future. 

Designs are still in progress, but can be seen here https://www.figma.com/file/P06HTzSyb9hExJVpwaUPmA/Honey-Pot-2.0?node-id=62%3A1381

![image.png](https://images.zenhubusercontent.com/5a2eb62e8a75884b908ab676/3d70243c-efe4-4165-ade9-5f6c91e905ae)

**Comment by onbjerg** [comment]
Solved in v2!
