### ISSUE TITLE
Challenge proposal: when using BYOT the token logic is not correct

### ISSUE THREAD

**Issue by 0xGabi** [1Hive/honey-pot#450]
When handling the Challenge action the logic should consider if the Garden has a `WrappableToken` and in that case use that on as the OGT instead. Now we are considering the OGT but the balances displayed are for the GDN token.

<img width="598" alt="Screen Shot 2021-05-22 at 3 06 00 PM" src="https://user-images.githubusercontent.com/9082013/119236862-0d2f3300-bb10-11eb-8736-bcdfc269d67f.png">

In the following picture, I have OGT balances and anyways the modal show me I don't.

<img width="598" alt="Screen Shot 2021-05-22 at 3 04 51 PM" src="https://user-images.githubusercontent.com/9082013/119236861-0a344280-bb10-11eb-8eb1-028c2e98c4d3.png">

**Comment by fabriziovigevani** [comment]
closed by #461
