### ISSUE TITLE
Collateral Manager: improve message when no data available

### ISSUE THREAD

**Issue by 0xGabi** [1Hive/honey-pot#451]
In the following image, I already did a deposit and a withdraw and there is no data.

<img width="1165" alt="Screen Shot 2021-05-22 at 3 03 27 PM" src="https://user-images.githubusercontent.com/9082013/119236950-a100ff00-bb10-11eb-97c5-11852d764c9e.png">

**Comment by 0xGabi** [comment]
I was wrong. The data is showing when you create a proposal. Maybe we can consider adding a bit more of context when there is no data to better understand what to expect.

<img width="1399" alt="Screen Shot 2021-05-22 at 3 26 20 PM" src="https://user-images.githubusercontent.com/9082013/119237214-13beaa00-bb12-11eb-8a36-8a85165d7a66.png">

**Comment by rperez89** [comment]
> I was wrong. The data is showing when the collateral is actually used. Data is not keeping track of deposits and withdraws. Maybe we can consider adding a bit more context when there is no data to better understand what to expect.
> 
> <img alt="Screen Shot 2021-05-22 at 3 26 20 PM" width="1399" src="https://user-images.githubusercontent.com/9082013/119237214-13beaa00-bb12-11eb-8a36-8a85165d7a66.png">

ah yes we are showing only the actions , so we need to change that no data available for something like "no collateral movements available"? cc @fioreb

**Comment by fioreb** [comment]
Yes, I think we Can use something like what Ro suggested!

**Comment by rperez89** [comment]
closed by #496
