### ISSUE TITLE
Metrics: BYOT Gardens not showing the right information

### ISSUE THREAD

**Issue by 0xGabi** [1Hive/honey-pot#453]
As shown in the image below, the token supply shows the `GDN` balance. We should decide if we want to show the `OGT` balance instead or change the description for that metric on BYOT Gardens. Maybe both 🤔

The component shows the `GDN` token price but for BYOT Gardens makes sense to show the `OGT` token price.

<img width="1500" alt="Screen Shot 2021-05-21 at 9 09 26 PM" src="https://user-images.githubusercontent.com/9082013/119237049-37cdbb80-bb11-11eb-80c8-56a5d722c16e.png">

**Comment by rperez89** [comment]
this one should be fixed with #457

**Comment by fabriziovigevani** [comment]
Closed by #457
