### ISSUE TITLE
Create proposal: support a custom link to the Garden's forum

### ISSUE THREAD

**Issue by 0xGabi** [1Hive/honey-pot#454]
Make sure we support a custom link that points to the Garden's forum that was configured on the `dao-list` package.

<img width="603" alt="Screen Shot 2021-05-22 at 3 30 38 PM" src="https://user-images.githubusercontent.com/9082013/119237387-eb837b00-bb12-11eb-8b80-e57c7af0dde6.png">

**Comment by rperez89** [comment]
ah nice one gaby

**Comment by 0xGabi** [comment]
Giveth already notice this and suggest the following: 
"Consider giving Gardens the ability to plug in their own forum for linking proposals (ie. gov.giveth.io, which doesn't even exist yet); right now creating a proposal requires a link to 1hive's forum"
