### ISSUE TITLE
Orgs break when no funds in the common pool.

### ISSUE THREAD

**Issue by fabriziovigevani** [1Hive/honey-pot#46]
As noted by @Evalir, orgs without funds in the common pool break after creating a proposal.

This is due to the threshold being `null` which causes `invalid` divisions.

**Comment by PierrickGT** [comment]
Could we have a workflow to reproduce and fix this bug?
Pretty difficult to try to fix a bug without any way to reproduce, especially when you are new to a project. :)

**Comment by PierrickGT** [comment]
@fabriziovigevani I think this bug has already been fixed by this commit: https://github.com/1Hive/honey-pot/commit/320201678243223b6758c573980477a670c71755

**Comment by fabriziovigevani** [comment]
Yes you are right!

closing..
