### ISSUE TITLE
Proposal: request show wrong error about not having enough funds in organization

### ISSUE THREAD

**Issue by 0xGabi** [1Hive/honey-pot#494]
https://gardens-rinkeby.1hive.org/#/garden/0xda1b46663b5ba949f6213d7c3135080b32ad2295/proposal/2

<img width="1907" alt="Screen Shot 2021-05-30 at 4 53 29 PM" src="https://user-images.githubusercontent.com/9082013/120118167-9b866300-c167-11eb-8dc1-eb0b237e1129.png">

**Comment by rperez89** [comment]
closed by #495
