### ISSUE TITLE
Add animation to Select type of garden step

### ISSUE THREAD

**Issue by fioreb** [1Hive/honey-pot#526]
When the user hovers one of the Type of Garden box, an animation should happen for each type of garden.

Here you can find the prototype:
 https://www.figma.com/proto/ySHlXMwz5elSXKI3feisJU/Gardens-wizard-creation-UI?page-id=495%3A3797&node-id=495%3A4961&viewport=-522%2C177%2C0.2327711433172226&scaling=min-zoom
(To see it change the page of the presentation with the arrows)

**Requirements:**
The animation should only happen once (stop looping)
After the user clicks the box, this should happen:
https://www.figma.com/proto/ySHlXMwz5elSXKI3feisJU/Gardens-wizard-creation-UI?page-id=495%3A3797&node-id=495%3A7918&viewport=-522%2C177%2C0.2327711433172226&scaling=min-zoom
And then change to the next step.

Here you can find the json files with the animations:
[https://app.zenhub.com/files/273752093/23ec6f89-6856-4076-af02-2a0da7774e18/download](https://app.zenhub.com/files/273752093/23ec6f89-6856-4076-af02-2a0da7774e18/download)

**Comment by 0xGabi** [comment]
Hey @lkngtn, how do you feel trying it with this issue?
