### ISSUE TITLE
Move config into his own object

### ISSUE THREAD

**Issue by rperez89** [1Hive/honey-pot#59]
Right now we are spreading the config with all the useAppData https://github.com/1Hive/honey-pot/blob/f62122f17cc2bd3c53e7d1e3e252514b837a3c7c/src/hooks/useOrgHooks.js#L112, it would be nice to move the config inside an object when this pr get merged https://github.com/1Hive/honey-pot/pull/58

**Comment by PierrickGT** [comment]
I've moved the config inside his own object in the following PR: https://github.com/1Hive/honey-pot/pull/68/commits/447cce12a566c09042ca168481ead458b8246ced

**Comment by metaverde** [comment]
So then is this issue closed?

**Comment by PierrickGT** [comment]
@metaverde the Pull Request is still open and I'm waiting for a review: https://github.com/1Hive/honey-pot/pull/68
