### ISSUE TITLE
Proposal detail: Change support slider

### ISSUE THREAD

**Issue by rperez89** [1Hive/honey-pot#60]
As reported by @Evalir on the aragon network dashboard there is some rounding issue when your available token amount is a decimal like 6.99999 and you select 100% on the slide bar will try to stake 7 tokens and will fail.

<img width="1111" alt="Screen Shot 2020-08-28 at 1 18 27 PM" src="https://user-images.githubusercontent.com/11763623/91590125-3c25c900-e931-11ea-9efa-90b79ba18370.png">

**Comment by PierrickGT** [comment]
@rperez89 I'm not sure this is a rounding issue. The code determining the input value is the following: https://github.com/1Hive/honey-pot/blob/a649de1f1a3daeebac148cf81b220fe1c641dc0b/src/components/ProposalActions.js#L38

So of course if in your example, you've supported the proposal with an amount of 1 CVTN the value will be `689 + 1 = 690`

**Comment by fabriziovigevani** [comment]
The problem is that we determine the max amount to stake from the formatted number https://github.com/1Hive/honey-pot/blob/a649de1f1a3daeebac148cf81b220fe1c641dc0b/src/components/ProposalActions.js#L47
and it can round up.
