### ISSUE TITLE
Transaction Modal for challenging a proposal needs text updates

### ISSUE THREAD

**Issue by divine-comedian** [1Hive/honey-pot#607]
On this page here we need to execute three transactions in order to send the on-chain event of challenging a proposal. The first two transactions are clearly explained.. but the third simply says third transaction. Perhaps we could provide more accurate info such as "Execute Challenge" or "Send Challenge"

Also because of the default text that appears in green when a transaction is successfully completed it risks getting very crowded with text on the page. for this particular modal you could get away with cutting the second sentence and simply say "Your transaction has successfully been processed!"

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/8b242b1d-424e-455f-8671-3f9494d15e16)

**Comment by fabriziovigevani** [comment]
closed by https://github.com/1Hive/honey-pot/pull/632
