### ISSUE TITLE
Transaction Modal for wrapping tokens needs text update

### ISSUE THREAD

**Issue by divine-comedian** [1Hive/honey-pot#608]
When we need to wrap tokens on a BYOT Garden we arrive at the transaction modal - 

![image](https://user-images.githubusercontent.com/67759413/132584977-9eb2984e-2750-4adb-847f-e834414aa433.png)

The second transaction simply says "Second Transaction" we could provide more context by changing this text to "Wrap Tokens"

**Comment by fabriziovigevani** [comment]
closed by https://github.com/1Hive/honey-pot/pull/632
