### ISSUE TITLE
Fix blockscout link

### ISSUE THREAD

**Issue by eenti** [1Hive/honey-pot#611]
When interacting in the Honeypot, the blockscout link associated does not work.

It sends you to 'blockscout.com/poa/xdai/txs/0x00...00' whereas blockscout now uses 'blockscout.com/xdai/mainnet/tx/0x00...00'

**Comment by fabriziovigevani** [comment]
closed by #625

**Comment by Blazingthirdeye** [comment]
Thank you Fabrizio.
