### ISSUE TITLE
Transferred currently active HNY but UI does not display decreased HNY amount.

### ISSUE THREAD

**Issue by willjgriff** [1Hive/honey-pot#87]
I transferred 5 HNY out of the top account in this list, displayed on this proposal: https://1hive.org/#/proposal/19 so it should display 36.19 HNY but still displays 41.19.

<img width="293" alt="Screenshot 2020-09-23 at 12 16 00" src="https://user-images.githubusercontent.com/9317743/94005738-9e3de680-fd96-11ea-9211-d23b470eed05.png">

**Comment by fabriziovigevani** [comment]
Closing as the issue was due to the app not being registered as a hook
