### ISSUE TITLE
Improve UI for mobile

### ISSUE THREAD

**Issue by sembrestels** [1Hive/honey-pot#89]
Proposal titles in conviction voting don't wrap:

**Proposals page**
![Screenshot from 2020-09-28 15-15-57](https://user-images.githubusercontent.com/931684/94437161-abdfdb80-019d-11eb-90d1-ed88e5652631.png)

**Proposal detail**
![Screenshot from 2020-09-28 15-18-21](https://user-images.githubusercontent.com/931684/94437386-f8c3b200-019d-11eb-84bd-af81a91bf97e.png)

**Comment by anthonyoliai** [comment]
I think as of #91 this can be closed.
