### ISSUE TITLE
Small suggestion to add other currencies to display prices of HNY

### ISSUE THREAD

**Issue by anthonyoliai** [1Hive/honey-pot#98]
Just a small proposal, not really an issue. Someone mentioned on Discord whether it was possible to change it so that Honey is displayed in another currency rather than USD. This could be nice for some users. It's just a small feature, which adds a little bit more functionality for users that are used to other currencies. I could perhaps look into it. We could for example create a small button on the top right, which allows for the user to choose their preferred currency.

**Comment by felixbbertrand** [comment]
This have been done also! @onbjerg (sorry for the ping)
